// <auto-generated />
using System;
using AK_HighSchool_App._AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AK_HighSchool_App.Migrations
{
    [DbContext(typeof(AbbDbContext))]
    partial class AbbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AK_HighSchool_App.Models.Relation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("GPA")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("StudyType")
                        .HasColumnType("int");

                    b.Property<int>("studentIDFK")
                        .HasColumnType("int");

                    b.Property<int>("subjectIDFK")
                        .HasColumnType("int");

                    b.Property<int>("teacherIDFK")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("studentIDFK");

                    b.HasIndex("subjectIDFK");

                    b.HasIndex("teacherIDFK");

                    b.ToTable("Relations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            GPA = 1,
                            Level = 2,
                            StudyType = 0,
                            studentIDFK = 1,
                            subjectIDFK = 7,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 2,
                            GPA = 2,
                            Level = 1,
                            StudyType = 1,
                            studentIDFK = 1,
                            subjectIDFK = 10,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 3,
                            GPA = 4,
                            Level = 0,
                            StudyType = 1,
                            studentIDFK = 2,
                            subjectIDFK = 1,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 4,
                            GPA = 3,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 2,
                            subjectIDFK = 3,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 5,
                            GPA = 0,
                            Level = 2,
                            StudyType = 0,
                            studentIDFK = 3,
                            subjectIDFK = 4,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 6,
                            GPA = 0,
                            Level = 1,
                            StudyType = 0,
                            studentIDFK = 3,
                            subjectIDFK = 5,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 7,
                            GPA = 0,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 3,
                            subjectIDFK = 6,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 8,
                            GPA = 3,
                            Level = 1,
                            StudyType = 1,
                            studentIDFK = 4,
                            subjectIDFK = 3,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 9,
                            GPA = 1,
                            Level = 2,
                            StudyType = 1,
                            studentIDFK = 5,
                            subjectIDFK = 4,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 10,
                            GPA = 2,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 6,
                            subjectIDFK = 5,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 11,
                            GPA = 4,
                            Level = 0,
                            StudyType = 0,
                            studentIDFK = 7,
                            subjectIDFK = 1,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 12,
                            GPA = 3,
                            Level = 1,
                            StudyType = 1,
                            studentIDFK = 8,
                            subjectIDFK = 6,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 13,
                            GPA = 0,
                            Level = 2,
                            StudyType = 1,
                            studentIDFK = 10,
                            subjectIDFK = 8,
                            teacherIDFK = 4
                        },
                        new
                        {
                            ID = 14,
                            GPA = 4,
                            Level = 1,
                            StudyType = 0,
                            studentIDFK = 10,
                            subjectIDFK = 11,
                            teacherIDFK = 4
                        },
                        new
                        {
                            ID = 15,
                            GPA = 0,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 11,
                            subjectIDFK = 9,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 16,
                            GPA = 3,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 11,
                            subjectIDFK = 12,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 17,
                            GPA = 1,
                            Level = 2,
                            StudyType = 2,
                            studentIDFK = 12,
                            subjectIDFK = 6,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 18,
                            GPA = 2,
                            Level = 1,
                            StudyType = 1,
                            studentIDFK = 12,
                            subjectIDFK = 7,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 19,
                            GPA = 0,
                            Level = 0,
                            StudyType = 0,
                            studentIDFK = 12,
                            subjectIDFK = 10,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 20,
                            GPA = 5,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 13,
                            subjectIDFK = 8,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 21,
                            GPA = 0,
                            Level = 2,
                            StudyType = 2,
                            studentIDFK = 13,
                            subjectIDFK = 11,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 22,
                            GPA = 4,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 14,
                            subjectIDFK = 9,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 23,
                            GPA = 0,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 14,
                            subjectIDFK = 12,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 24,
                            GPA = 0,
                            Level = 0,
                            StudyType = 1,
                            studentIDFK = 15,
                            subjectIDFK = 1,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 25,
                            GPA = 1,
                            Level = 1,
                            StudyType = 1,
                            studentIDFK = 15,
                            subjectIDFK = 2,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 26,
                            GPA = 0,
                            Level = 0,
                            StudyType = 0,
                            studentIDFK = 15,
                            subjectIDFK = 3,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 27,
                            GPA = 3,
                            Level = 1,
                            StudyType = 0,
                            studentIDFK = 16,
                            subjectIDFK = 4,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 28,
                            GPA = 0,
                            Level = 2,
                            StudyType = 2,
                            studentIDFK = 16,
                            subjectIDFK = 5,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 29,
                            GPA = 4,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 16,
                            subjectIDFK = 6,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 30,
                            GPA = 0,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 17,
                            subjectIDFK = 7,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 31,
                            GPA = 3,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 18,
                            subjectIDFK = 8,
                            teacherIDFK = 4
                        },
                        new
                        {
                            ID = 32,
                            GPA = 1,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 19,
                            subjectIDFK = 4,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 33,
                            GPA = 2,
                            Level = 1,
                            StudyType = 0,
                            studentIDFK = 19,
                            subjectIDFK = 5,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 34,
                            GPA = 2,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 20,
                            subjectIDFK = 4,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 35,
                            GPA = 3,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 20,
                            subjectIDFK = 5,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 36,
                            GPA = 0,
                            Level = 2,
                            StudyType = 0,
                            studentIDFK = 20,
                            subjectIDFK = 6,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 37,
                            GPA = 1,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 20,
                            subjectIDFK = 7,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 38,
                            GPA = 0,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 20,
                            subjectIDFK = 10,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 39,
                            GPA = 0,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 21,
                            subjectIDFK = 10,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 40,
                            GPA = 5,
                            Level = 1,
                            StudyType = 0,
                            studentIDFK = 21,
                            subjectIDFK = 11,
                            teacherIDFK = 4
                        },
                        new
                        {
                            ID = 41,
                            GPA = 0,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 21,
                            subjectIDFK = 12,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 42,
                            GPA = 3,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 22,
                            subjectIDFK = 9,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 43,
                            GPA = 0,
                            Level = 2,
                            StudyType = 2,
                            studentIDFK = 22,
                            subjectIDFK = 12,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 44,
                            GPA = 4,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 23,
                            subjectIDFK = 1,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 45,
                            GPA = 2,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 23,
                            subjectIDFK = 2,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 46,
                            GPA = 3,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 23,
                            subjectIDFK = 3,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 47,
                            GPA = 1,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 24,
                            subjectIDFK = 4,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 48,
                            GPA = 2,
                            Level = 1,
                            StudyType = 1,
                            studentIDFK = 24,
                            subjectIDFK = 5,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 49,
                            GPA = 2,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 24,
                            subjectIDFK = 6,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 50,
                            GPA = 3,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 25,
                            subjectIDFK = 8,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 51,
                            GPA = 1,
                            Level = 2,
                            StudyType = 2,
                            studentIDFK = 25,
                            subjectIDFK = 11,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 52,
                            GPA = 0,
                            Level = 1,
                            StudyType = 0,
                            studentIDFK = 26,
                            subjectIDFK = 7,
                            teacherIDFK = 4
                        },
                        new
                        {
                            ID = 53,
                            GPA = 2,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 26,
                            subjectIDFK = 9,
                            teacherIDFK = 4
                        },
                        new
                        {
                            ID = 54,
                            GPA = 4,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 27,
                            subjectIDFK = 7,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 55,
                            GPA = 2,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 27,
                            subjectIDFK = 8,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 56,
                            GPA = 3,
                            Level = 1,
                            StudyType = 1,
                            studentIDFK = 27,
                            subjectIDFK = 10,
                            teacherIDFK = 4
                        },
                        new
                        {
                            ID = 57,
                            GPA = 1,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 27,
                            subjectIDFK = 11,
                            teacherIDFK = 4
                        },
                        new
                        {
                            ID = 58,
                            GPA = 5,
                            Level = 1,
                            StudyType = 0,
                            studentIDFK = 27,
                            subjectIDFK = 5,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 59,
                            GPA = 2,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 28,
                            subjectIDFK = 4,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 60,
                            GPA = 3,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 28,
                            subjectIDFK = 5,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 61,
                            GPA = 1,
                            Level = 2,
                            StudyType = 1,
                            studentIDFK = 28,
                            subjectIDFK = 6,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 62,
                            GPA = 0,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 28,
                            subjectIDFK = 9,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 63,
                            GPA = 4,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 28,
                            subjectIDFK = 12,
                            teacherIDFK = 5
                        },
                        new
                        {
                            ID = 64,
                            GPA = 4,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 29,
                            subjectIDFK = 7,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 65,
                            GPA = 2,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 29,
                            subjectIDFK = 8,
                            teacherIDFK = 3
                        },
                        new
                        {
                            ID = 66,
                            GPA = 3,
                            Level = 1,
                            StudyType = 1,
                            studentIDFK = 30,
                            subjectIDFK = 1,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 67,
                            GPA = 1,
                            Level = 1,
                            StudyType = 2,
                            studentIDFK = 30,
                            subjectIDFK = 2,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 68,
                            GPA = 5,
                            Level = 1,
                            StudyType = 0,
                            studentIDFK = 30,
                            subjectIDFK = 3,
                            teacherIDFK = 1
                        },
                        new
                        {
                            ID = 69,
                            GPA = 2,
                            Level = 0,
                            StudyType = 2,
                            studentIDFK = 30,
                            subjectIDFK = 4,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 70,
                            GPA = 3,
                            Level = 1,
                            StudyType = 1,
                            studentIDFK = 30,
                            subjectIDFK = 5,
                            teacherIDFK = 2
                        },
                        new
                        {
                            ID = 71,
                            GPA = 1,
                            Level = 2,
                            StudyType = 2,
                            studentIDFK = 30,
                            subjectIDFK = 6,
                            teacherIDFK = 2
                        });
                });

            modelBuilder.Entity("AK_HighSchool_App.Models.student", b =>
                {
                    b.Property<int>("studentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentID"), 1L, 1);

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("studentAge")
                        .HasColumnType("int");

                    b.Property<string>("studentFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("studentLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("studentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            studentID = 1,
                            Gender = 0,
                            email = "Anderss@gmail.com",
                            password = "AndG1234",
                            studentAge = 48,
                            studentFirstName = "Anderss",
                            studentLastName = "Gappi",
                            userName = "AnderssG"
                        },
                        new
                        {
                            studentID = 2,
                            Gender = 1,
                            email = "maria@gmail.com",
                            password = "MarE1234",
                            studentAge = 42,
                            studentFirstName = "Maria",
                            studentLastName = "Erik",
                            userName = "MariaK"
                        },
                        new
                        {
                            studentID = 3,
                            Gender = 1,
                            email = "Anna@gmail.com",
                            password = "AnaL1234",
                            studentAge = 38,
                            studentFirstName = "Anna",
                            studentLastName = "Lars",
                            userName = "AnnaL"
                        },
                        new
                        {
                            studentID = 4,
                            Gender = 1,
                            email = "Christina@gmail.com",
                            password = "ChrP1234",
                            studentAge = 29,
                            studentFirstName = "Christina",
                            studentLastName = "Peter",
                            userName = "ChristinaP"
                        },
                        new
                        {
                            studentID = 5,
                            Gender = 0,
                            email = "Johan@gmail.com",
                            password = "JuhG1234",
                            studentAge = 52,
                            studentFirstName = "Johan",
                            studentLastName = "Gunner",
                            userName = "JuhanG"
                        },
                        new
                        {
                            studentID = 6,
                            Gender = 0,
                            email = "Oskar@gmail.com",
                            password = "OskM1234",
                            studentAge = 33,
                            studentFirstName = "Oskar",
                            studentLastName = "Michal",
                            userName = "OskarM"
                        },
                        new
                        {
                            studentID = 7,
                            Gender = 0,
                            email = "Erik@gmail.com",
                            password = "EriB1234",
                            studentAge = 32,
                            studentFirstName = "Erik",
                            studentLastName = "Bjork",
                            userName = "ErikB"
                        },
                        new
                        {
                            studentID = 8,
                            Gender = 1,
                            email = "Camilla@gmail.com",
                            password = "CamN234",
                            studentAge = 26,
                            studentFirstName = "Kamilla",
                            studentLastName = "Nystrom",
                            userName = "Camilla"
                        },
                        new
                        {
                            studentID = 9,
                            Gender = 1,
                            email = "Eva@gmail.com",
                            password = "EvaE1234",
                            studentAge = 24,
                            studentFirstName = "Eva",
                            studentLastName = "Eriksson",
                            userName = "EvaE"
                        },
                        new
                        {
                            studentID = 10,
                            Gender = 0,
                            email = "Carl@gmail.com",
                            password = "CarlO1234",
                            studentAge = 30,
                            studentFirstName = "Carl",
                            studentLastName = "Olsson",
                            userName = "CarlO"
                        },
                        new
                        {
                            studentID = 11,
                            Gender = 0,
                            email = "Marcus@gmail.com",
                            password = "MarF1234",
                            studentAge = 41,
                            studentFirstName = "Marcus",
                            studentLastName = "Fredrik",
                            userName = "Marcus"
                        },
                        new
                        {
                            studentID = 12,
                            Gender = 1,
                            email = "Lena@gmail.com",
                            password = "LenaG1234",
                            studentAge = 34,
                            studentFirstName = "Lena",
                            studentLastName = "Gunner",
                            userName = "LenaG"
                        },
                        new
                        {
                            studentID = 13,
                            Gender = 1,
                            email = "Hanna@gmail.com",
                            password = "HanB1234",
                            studentAge = 38,
                            studentFirstName = "Hanna",
                            studentLastName = "Bjorn",
                            userName = "HannaB"
                        },
                        new
                        {
                            studentID = 14,
                            Gender = 0,
                            email = "Robert@gmail.com",
                            password = "RobA1234",
                            studentAge = 25,
                            studentFirstName = "Robert",
                            studentLastName = "Ali",
                            userName = "RobertA"
                        },
                        new
                        {
                            studentID = 15,
                            Gender = 0,
                            email = "William@gmail.com",
                            password = "JuhG1234",
                            studentAge = 36,
                            studentFirstName = "Johan",
                            studentLastName = "Gunner",
                            userName = "JuhanG"
                        },
                        new
                        {
                            studentID = 16,
                            Gender = 0,
                            email = "Anderss@gmail.com",
                            password = "WilH1234",
                            studentAge = 48,
                            studentFirstName = "William",
                            studentLastName = "Hinrik",
                            userName = "WilliamH"
                        },
                        new
                        {
                            studentID = 17,
                            Gender = 1,
                            email = "Elsa@gmail.com",
                            password = "ElsF1234",
                            studentAge = 23,
                            studentFirstName = "Elsa",
                            studentLastName = "Forsberg",
                            userName = "ElsaF"
                        },
                        new
                        {
                            studentID = 18,
                            Gender = 0,
                            email = "Dan@gmail.com",
                            password = "DanE1234",
                            studentAge = 29,
                            studentFirstName = "Dan",
                            studentLastName = "Eklund",
                            userName = "DanE"
                        },
                        new
                        {
                            studentID = 19,
                            Gender = 0,
                            email = "David@gmail.com",
                            password = "DavG1234",
                            studentAge = 35,
                            studentFirstName = "David",
                            studentLastName = "Gunnel",
                            userName = "DavidG"
                        },
                        new
                        {
                            studentID = 20,
                            Gender = 0,
                            email = "Johan@gmail.com",
                            password = "JuhG1234",
                            studentAge = 52,
                            studentFirstName = "Karolin",
                            studentLastName = "Holm",
                            userName = "KarolinH"
                        },
                        new
                        {
                            studentID = 21,
                            Gender = 1,
                            email = "Emma@gmail.com",
                            password = "EmmJ1234",
                            studentAge = 41,
                            studentFirstName = "Emma",
                            studentLastName = "Johansson",
                            userName = "EmmaJ"
                        },
                        new
                        {
                            studentID = 22,
                            Gender = 1,
                            email = "Astrid@gmail.com",
                            password = "AstL1234",
                            studentAge = 30,
                            studentFirstName = "Astrid",
                            studentLastName = "Lars",
                            userName = "AstridL"
                        },
                        new
                        {
                            studentID = 23,
                            Gender = 0,
                            email = "Karl@gmail.com",
                            password = "KarN1234",
                            studentAge = 37,
                            studentFirstName = "Karl",
                            studentLastName = "Nils",
                            userName = "KarlN"
                        },
                        new
                        {
                            studentID = 24,
                            Gender = 0,
                            email = "Hans@gmail.com",
                            password = "HanR1234",
                            studentAge = 36,
                            studentFirstName = "Hans",
                            studentLastName = "Roberto",
                            userName = "HansR"
                        },
                        new
                        {
                            studentID = 25,
                            Gender = 1,
                            email = "Asa@gmail.com",
                            password = "AsaS1234",
                            studentAge = 35,
                            studentFirstName = "Asa",
                            studentLastName = "Sven",
                            userName = "AsaS"
                        },
                        new
                        {
                            studentID = 26,
                            Gender = 0,
                            email = "Per@gmail.com",
                            password = "PerT1234",
                            studentAge = 43,
                            studentFirstName = "Per",
                            studentLastName = "Tomas",
                            userName = "PerT"
                        },
                        new
                        {
                            studentID = 27,
                            Gender = 1,
                            email = "Kristin@gmail.com",
                            password = "KrsT1234",
                            studentAge = 31,
                            studentFirstName = "Kristin",
                            studentLastName = "Magnus",
                            userName = "KristinM"
                        },
                        new
                        {
                            studentID = 28,
                            Gender = 0,
                            email = "Fredrik@gmail.com",
                            password = "FreS1234",
                            studentAge = 29,
                            studentFirstName = "Fredrik",
                            studentLastName = "Simon",
                            userName = "FredrikS"
                        },
                        new
                        {
                            studentID = 29,
                            Gender = 1,
                            email = "Brigitta@gmail.com",
                            password = "BigL1234",
                            studentAge = 51,
                            studentFirstName = "Brigitta",
                            studentLastName = "Larsson",
                            userName = "BrigittaL"
                        },
                        new
                        {
                            studentID = 30,
                            Gender = 0,
                            email = "Filip@gmail.com",
                            password = "FilA1234",
                            studentAge = 44,
                            studentFirstName = "Filip",
                            studentLastName = "Anton",
                            userName = "FilipA"
                        });
                });

            modelBuilder.Entity("AK_HighSchool_App.Models.subject", b =>
                {
                    b.Property<int>("subjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subjectID"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("DataBase")
                        .HasColumnType("int");

                    b.Property<int?>("GraphicDesign")
                        .HasColumnType("int");

                    b.Property<int?>("Programming")
                        .HasColumnType("int");

                    b.Property<int?>("WebbDevelopment")
                        .HasColumnType("int");

                    b.HasKey("subjectID");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            subjectID = 1,
                            Category = 0,
                            GraphicDesign = 0
                        },
                        new
                        {
                            subjectID = 2,
                            Category = 0,
                            GraphicDesign = 1
                        },
                        new
                        {
                            subjectID = 3,
                            Category = 0,
                            GraphicDesign = 2
                        },
                        new
                        {
                            subjectID = 4,
                            Category = 1,
                            WebbDevelopment = 0
                        },
                        new
                        {
                            subjectID = 5,
                            Category = 1,
                            WebbDevelopment = 1
                        },
                        new
                        {
                            subjectID = 6,
                            Category = 1,
                            WebbDevelopment = 2
                        },
                        new
                        {
                            subjectID = 7,
                            Category = 2,
                            Programming = 0
                        },
                        new
                        {
                            subjectID = 8,
                            Category = 2,
                            Programming = 1
                        },
                        new
                        {
                            subjectID = 9,
                            Category = 2,
                            Programming = 2
                        },
                        new
                        {
                            subjectID = 10,
                            Category = 3,
                            DataBase = 0
                        },
                        new
                        {
                            subjectID = 11,
                            Category = 3,
                            DataBase = 1
                        },
                        new
                        {
                            subjectID = 12,
                            Category = 3,
                            DataBase = 2
                        });
                });

            modelBuilder.Entity("AK_HighSchool_App.Models.teacher", b =>
                {
                    b.Property<int>("teacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacherID"), 1L, 1);

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("teacherAge")
                        .HasColumnType("int");

                    b.Property<string>("teacherFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("teacherLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("teacherID");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            teacherID = 1,
                            Gender = 1,
                            teacherAge = 44,
                            teacherFirstName = "Helen",
                            teacherLastName = "Fredrik"
                        },
                        new
                        {
                            teacherID = 2,
                            Gender = 0,
                            teacherAge = 38,
                            teacherFirstName = "Peter",
                            teacherLastName = "Rolf"
                        },
                        new
                        {
                            teacherID = 3,
                            Gender = 0,
                            teacherAge = 42,
                            teacherFirstName = "Lars",
                            teacherLastName = "Johnsson"
                        },
                        new
                        {
                            teacherID = 4,
                            Gender = 0,
                            teacherAge = 56,
                            teacherFirstName = "Filip",
                            teacherLastName = "Niklas"
                        },
                        new
                        {
                            teacherID = 5,
                            Gender = 1,
                            teacherAge = 36,
                            teacherFirstName = "Emilla",
                            teacherLastName = "Gunner"
                        });
                });

            modelBuilder.Entity("AK_HighSchool_App.Models.Relation", b =>
                {
                    b.HasOne("AK_HighSchool_App.Models.student", "Student")
                        .WithMany("studentTeachers")
                        .HasForeignKey("studentIDFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AK_HighSchool_App.Models.subject", "Subject")
                        .WithMany("teacherStudent")
                        .HasForeignKey("subjectIDFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AK_HighSchool_App.Models.teacher", "Teacher")
                        .WithMany("teacherStudent")
                        .HasForeignKey("teacherIDFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AK_HighSchool_App.Models.student", b =>
                {
                    b.Navigation("studentTeachers");
                });

            modelBuilder.Entity("AK_HighSchool_App.Models.subject", b =>
                {
                    b.Navigation("teacherStudent");
                });

            modelBuilder.Entity("AK_HighSchool_App.Models.teacher", b =>
                {
                    b.Navigation("teacherStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
